ignore:
  - "**/core/management/**/*.java"
  - "**/adaptris/test/**/*.java"
  - "**/*Test*.java"
  - "**/test/**/.*.java"
  - "**/com/adaptris/ftp/**/*.java"
  - "**/com/adaptris/sftp/**/*.java"
  - "**/core/jdbc/**/*.java"
  - "**/certificate/**/*.java"
  - "**/com/adaptrisjdbc/**/*.java"