coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 0.15%
    project:
      default:
        target: auto
        threshold: 0.15%
ignore:
  - "**/com/adaptris/core/management/"
  - "**/test/"
  - "**/com/adaptris/ftp/"
  - "**/com/adaptris/sftp/"
  - "**/com/adaptris/core/jdbc/"
  - "**/com/adaptris/security/certificate/"
  - "**/com/adaptris/jdbc/"
  - "**/com/adaptris/annotation/"
  - "**/com/adaptris/filetransfer/"
  - "**/com/adaptris/logging/jmx/"
  - "**/com/adaptris/logging/log4j2/JmxLogAppender.java"
  - "**/com/adaptris/taglet/"
  - "**/com/adaptris/validation/"
  - "**/com/adaptris/boot/"
