ignore:
  - "**/core/management/**/*.java"
  - "**/adaptris/test/**/*.java"
  - "**/*Test*.java"
  - "**/test/**/*.java"
  - "**/com/adaptris/ftp/**/*.java"
  - "**/com/adaptris/sftp/**/*.java"
  - "**/core/jdbc/**/*.java"
  - "**/certificate/**/*.java"
  - "**/com/adaptris/jdbc/**/*.java"
  - "**/com/adaptris/annotation/**/*.java"
  - "**/com/filetransfer/**/*.java"
  - "**/com/adaptris/logging/**/*.java"
  - "**/com/adaptris/taglet/**/*.java"
  - "**/com/adaptris/validation/**/*.java"
  - "**/com/adaptris/boot/**/*.java"
