extraction:
  java:
    index:
      java_version: 11
      # Run individual commands since otherwise you get implicit dependency issues.
      build_command:
        - ./gradlew -S :interlok-core-apt:lgtmCompile
        - ./gradlew -S :interlok-common:lgtmCompile
        - ./gradlew -S :interlok-logging:lgtmCompile
        - ./gradlew -S :interlok-boot:lgtmCompile
        - ./gradlew -S :interlok-core:lgtmCompile
        - ./gradlew -S :interlok-client:lgtmCompile
        - ./gradlew -S :interlok-client-jmx:lgtmCompile

path_classifiers:
  docs:
    - "LICENSE*"
    - "*.md"
    - "*.html"
  ci:
    - "appveyor.yml"
    - ".codecov.yml"
    - ".travis.yml"
    - ".circleci"
    - ".dependabot"
    - ".github"
    - ".lgtm.yml"
    - ".gitlab-ci.yml"
  generated:
    exclude: "**/*.java"
