language: java
sudo: required
dist: trusty

before_script:
  - echo "default.jdbc.storedproc.tests.enabled=true" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.url=jdbc:mysql://localhost:3306/" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.driver=com.mysql.jdbc.Driver" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.database=ci_travis" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.username=root" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.password=" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.vendor=mysql" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.teststatement=" >> interlok-core/build.properties
  - echo "default.jdbc.storedproc.url.params=?useSSL=false" >> interlok-core/build.properties

install: ./gradlew --version

script: ./gradlew --no-daemon -PverboseTests=true test jacocoTestReport

addons:
  apt:
    packages:
      - haveged
      - ant-optional
      - bash-builtins

before_install:
  - sudo service haveged start

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - openjdk8

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

branches:
  only:
  - develop
