language: java
sudo: required
dist: trusty

before_script:
  - echo "default.jdbc.storedproc.tests.enabled=true" >> adapter/build.properties
  - echo "default.jdbc.storedproc.url=jdbc:mysql://localhost:3306/" >> adapter/build.properties
  - echo "default.jdbc.storedproc.driver=com.mysql.jdbc.Driver" >> adapter/build.properties
  - echo "default.jdbc.storedproc.database=ci_travis" >> adapter/build.properties
  - echo "default.jdbc.storedproc.username=root" >> adapter/build.properties
  - echo "default.jdbc.storedproc.password=" >> adapter/build.properties
  - echo "default.jdbc.storedproc.vendor=mysql" >> adapter/build.properties
  - echo "default.jdbc.storedproc.teststatement=" >> adapter/build.properties

script: ant -Divy.logging=default test

addons:
  apt:
    packages:
      - haveged
      - ant-optional

before_install:
  - sudo service haveged start

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - openjdk8

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.ivy2

notifications:
  email: false

branches:
  only:
  - develop
