language: java
sudo: false
script: ant -Divy.logging=default -Djava.security.egd=file:/dev/./urandom test-no-reports
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2

notifications:
  email: false

branches:
  only:
  - develop
