language: java
sudo: required
dist: trusty

script: ant -Divy.logging=default test-no-reports

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-unlimited-jce-policy
      - haveged

before_install:
  - sudo service haveged start

jdk:
  - oraclejdk8

cache:
  apt: true
  directories:
    - $HOME/.ivy2

notifications:
  email: false

branches:
  only:
  - develop
