# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/interlok

    environment:
      JAVA_TOOL_OPTIONS: -Xmx2G
      GRADLE_OPTS: -Djava.security.egd=file:/dev/./urandom
      TERM: dumb

    steps:
      - run:
          name: Configure Gradle
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.warning.mode=none" > ~/.gradle/gradle.properties

      - run:
          name: Use /dev/urandom
          command: |
            sudo sed -i.bak -e "s/securerandom.source=file:\/dev\/random/securerandom.source=file:\/dev\/.\/urandom/g" -e "s/securerandom.strongAlgorithms=NativePRNGBlocking/securerandom.strongAlgorithms=NativePRNG/g" /etc/java-8-openjdk/security/java.security

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies


      # run tests!
      - run:
          name: Run Tests
          command: ./gradlew -PverboseTests=true test

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: dependencies{{ checksum "build.gradle" }}
