# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/interlok

    environment:
      TERM: dumb

    steps:
      - run:
          name: Configure Gradle
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.warning.mode=none" > ~/.gradle/gradle.properties
            echo "org.gradle.jvmargs=-Xmx2G -Djava.security.egd=file:/dev/./urandom" >> ~/.gradle/gradle.properties

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies


      # run tests!
      - run:
          name: Run Tests
          command: ./gradlew -PverboseTests=true test

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: dependencies{{ checksum "build.gradle" }}
